
title: My Resume
url: 'gabrielfelipevs.github.io'
baseurl: '/gabrielfelipevs.github.io' #change it according to your repository name



# Profile information
yourname: GABRIEL FELIPE  ## put your name
title: 'Student in control engineering and automation'  ## your title
location: Canada


## Social Profiles
facebook: https://www.facebook.com/gabriel.felipe.5686  ## your facebook account url
telegram: https://t.me/gabrielfvds ## your telegram account url
linkedin: https://www.linkedin.com/in/gabrielfelipevs ## your linkedin account url
strava: https://www.strava.com/athletes/4331753  ## you dribbble account url
github: https://github.com/gabrielfelipevs  ## your github account url



# Update all the sections by editing the files inside _includes folder.
